### ISSUE TITLE
Error al descargar un documento de RM especificando la versión

### ISSUE THREAD

**Issue by tgaya-dgtic** [GovernIB/gdib#109]
Cuando se intenta acceder a un documento en RM, por ejemplo un pades, añadiendo en la petición la versión antes del id del nodo (por ejemplo **1.0**@9f4b780f-0421-436a-9ea6-4a425b405073), da un error de permisos. Habría que comprobar si esto es normal.

Ejemplo:
```
REQUEST: https://esbse.caib.es:4430/esb/services/getDocument {"getDocumentRequest":{"serviceHeader":{"serviceVersion":"1.0","auditInfo":{"application":"XXX"},"securityInfo":{"user":"XXX","password":"XXX"}},"param":{"documentId":{"nodeId":"1.0@9f4b780f-0421-436a-9ea6-4a425b405073"},"content":"true"}}}
RESPONSE: {"exception":{"code": "COD_021","description": "010939344 Access Denied.  You do not have the appropriate permissions to perform this operation. - net.sf.acegisecurity.AccessDeniedException: Access is denied."}}
```

**Comment by CarlosDiez-inetum** [comment]
El documento no existe en el repositorio de ACS de desarrollo:
13:09:49 - 01163339 Node workspace://SpacesStore/9f4b780f-0421-436a-9ea6-4a425b405073 does not exist.

**Comment by tgaya-dgtic** [comment]
Por ejemplo, en vuestro entorno este documento 66b4690b-88a9-4e94-a0ed-4d930398581b
está en RM y tiene versionLabel: "1.0"

Exception in thread "main" es.caib.plugins.arxiu.caib.ArxiuCaibException: [HTTP_500, COD_021] 01163884 Exception in Transaction. - es.caib.gdib.ws.exception.GdibException: Could not have the permission of Read to perfom the operation
        at es.caib.plugins.arxiu.caib.ArxiuCaibClient.generarExcepcioJson(ArxiuCaibClient.java:255)
        at es.caib.plugins.arxiu.caib.ArxiuCaibClient.generarEnviarPeticio(ArxiuCaibClient.java:145)
        at es.caib.plugins.arxiu.caib.ArxiuPluginCaib.documentVersionsComu(ArxiuPluginCaib.java:1584)
        at es.caib.plugins.arxiu.caib.ArxiuPluginCaib.documentDarreraVersio(ArxiuPluginCaib.java:1619)
        at es.caib.plugins.arxiu.caib.ArxiuPluginCaib.documentDetalls(ArxiuPluginCaib.java:893)
        at client.ArxiuCaibClient.detallsDocument(ArxiuCaibClient.java:189)
        at client.ArxiuCaibClient.main(ArxiuCaibClient.java:813)

Os envío el fichero .java para generar este error por email.

**Comment by CarlosDiez-inetum** [comment]
Investigaremos el tema de los permisos, pero el principal problema que veo aquí es que se llama al método de obtener versiones sobre una versión concreta del documento. 

La ejecución de getNodeVersionList únicamente tiene sentido sobre el nodo sin especificar la versión. Si especificamos una versión, el Nodo que recupera proviene de una especie de snapshot del objeto Version.

**Comment by CarlosDiez-inetum** [comment]
Hemos estado debugueando las llamadas y se confirma la sospecha. Es un mal uso del método documentDetalls en IArxiuPlugin. El método documentDetalls hace una consulta a dos métodos SOAP: getDocVersionList y getDocument.

La rotura se produce en el getDocVersionList al indicar el 1.0@uuid. Explicación:

- Si especificamos la versión, el objeto Node recogido pertenece al **VersionStore**, que tiene permisos indeterminados en el repositorio. Es un nodo distinto, por así decirlo.
- Si no especificamos la versión, se recoge un objeto Node que pertenece al **Workspace** de Alfresco. Este es el nodo real con los permisos. 

Consideramos que el error es funcional por cómo está montada la consulta en el IArxiuPlugin o WSO2.

Adjunto capturas:
<img width="237" alt="NonVersionNode" src="https://user-images.githubusercontent.com/115004422/219620569-7eca6a04-63f5-4751-8976-56c1dad50557.png">
<img width="245" alt="VersionNode" src="https://user-images.githubusercontent.com/115004422/219620583-dfe6e4ea-6b66-4f56-ac88-6e9cb8d6df4e.png">

**Comment by tgaya-dgtic** [comment]
Tal vez convendría a partir de ahora enviaros las peticiones directas al bus, porque sí, el plugin realiza distintas llamadas intermedias.

De esta forma, las peticiones, serían por ejemplo:

```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
   <soapenv:Header/>
   <soapenv:Body>
      <jsonObject>
         <getDocVersionListRequest>
            <serviceHeader>
               <serviceVersion>1.0</serviceVersion>
               <auditInfo>
                  <application>PETICIONS_BUS2</application>
               </auditInfo>
               <securityInfo>
                  <user>XXX</user>
                  <password>XXX</password>
               </securityInfo>
            </serviceHeader>
            <param>
               <nodeId>66b4690b-88a9-4e94-a0ed-4d930398581b</nodeId>
            </param>
         </getDocVersionListRequest>
      </jsonObject>
   </soapenv:Body>
</soapenv:Envelope>
```

La respuesta es: 
```
<S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/">
   <S:Body>
      <csgd:getDocVersionListResult xmlns:csgd="urn:es.caib.archivodigital.esb.services:1.0.0">   
         <csgd:result>      
            <csgd:code>COD_000</csgd:code>      
            <csgd:description>Petición realizada correctamente.</csgd:description>   
         </csgd:result>   
         <csgd:resParam>      
            <csgd:id>1.0</csgd:id>      
            <csgd:date>2023-02-16T19:50:38.051+01:00</csgd:date>   
         </csgd:resParam>
      </csgd:getDocVersionListResult>
   </S:Body>
</S:Envelope>
```

Existe versión 1.0, entonces, la solicitamos:
```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
   <soapenv:Header/>
   <soapenv:Body>
      <jsonObject>
         <getDocumentRequest>
            <serviceHeader>
               <serviceVersion>1.0</serviceVersion>
               <auditInfo>
                  <application>PETICIONS_BUS2</application>
               </auditInfo>
               <securityInfo>
                  <user>XXX</user>
                  <password>XXX</password>
               </securityInfo>
            </serviceHeader>
            <param>
               <documentId>
                  <nodeId>1.0@66b4690b-88a9-4e94-a0ed-4d930398581b</nodeId>
               </documentId>
               <content>true</content>
            </param>
         </getDocumentRequest>
      </jsonObject>
   </soapenv:Body>
</soapenv:Envelope>
```

y responde con el error
```
<S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/" xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
   <SOAP-ENV:Header/>
   <S:Body xmlns:ns3="http://www.w3.org/2003/05/soap-envelope">
      <jsonObject>
         <exception>
            <code>COD_021</code>
            <description>01205399 Access Denied.  You do not have the appropriate permissions to perform this operation. - net.sf.acegisecurity.AccessDeniedException: Access is denied.</description>
         </exception>
      </jsonObject>
   </S:Body>
</S:Envelope>
```

**Comment by CesarGarcia-inetum** [comment]
Hemos realizado las pruebas pertinentes respecto a la consulata de documentos por versiones desde ArxiuCAIBClient. Aquí interviene la lógica de 3 componentes (IArxiuPlugin, BUS, GDIB Alfresco).

Caso 1: Las pruebas desde el plugin de ArxiuCAIBClient no son correctas a nivel funcional, ya que se pasa la versión dentro del parámetro "identificador", en vez del parámetro "versio" del método "documentDetalls".
Caso 2: Si el documento se encuentra en el Site del RM, la consulta sobre la versión específica de un documento produce un error de acceso denegado debido a un control del interceptor del RM. "org.alfresco.module.org_alfresco_module_rm.security.RMMethodSecurityInterceptor"

*Hemos creado un caso con Hyland-Alfresco respecto a esta funcionalidad en el RM, ya que actualmente estáis en una versión de AGS 3.4, habiendo nuevas versiones disponibles por el fabricante para veriosnes de ACS > 7

Esta incidencia está relacionada con las incidencias abiertas [#107](https://github.com/GovernIB/gdib/issues/107) y [#111](https://github.com/GovernIB/gdib/issues/111)

**Comment by tgaya-dgtic** [comment]
Compilado el código que subísteis ayer y desplegado, hechas pruebas, parece que va bien.

```
{
  "getDocumentRequest": {
    "serviceHeader": {
      "serviceVersion": "1.0",
      "auditInfo": {
        "application": "PETICIONS_BUS2"
      },
      "securityInfo": {
        "user": "app1",
        "password": "XXXXX"
      }
    },
    "param": {
      "documentId": {
        "nodeId": "1.0@66b4690b-88a9-4e94-a0ed-4d930398581b"
      },
      "content": "true"
    }
  }
}

{
  "getDocumentResult": {
    "result": {
      "code": "COD_000",
      "description": "Petición realizada correctamente."
    },
    "resParam": {
      "id": "66b4690b-88a9-4e94-a0ed-4d930398581b",
      "type": "eni:documento",
      "name": "A3_v3_signed (2023-1676573438584).pdf",
      "aspects": [
        "eni:firmadoBase",
        "eni:transferible",
        "eni:firmado",
        "eni:interoperable"
      ],
      "metadataCollection": [
        {
          "qname": "eni:tipoFirma",
          "value": "TF06"
        }
...
```
