### ISSUE TITLE
setFinalDocument no hace upgrade de firma

### ISSUE THREAD

**Issue by tgaya-dgtic** [GovernIB/gdib#115]
Cuando se sube un documento como definitivo, se hace upgrade de firma.

Si se sube un documento como borrador y luego se marca como definitivo, con la operación setFinalDocument, no se hace upgrade de firma, y debería también hacerse. Se añade el metadato "eni:perfil_firma" : "LTV", lo cual no es cierto.
Ejemplo documento: c81b7558-f1bc-4c53-bfa8-02e00468c18d

**Comment by tgaya-dgtic** [comment]
Creo que ya he identificado cómo reproducir el error.

Ejemplo:

```
expediente f0d9ab99-a99f-4b53-8ea9-479d0f5dbd20

A1_v1_signed.pdf 71e75be8-2571-4089-8840-e1019a56ef65
 signat -> PAdES-LTV
 marcat com a definitiu -> PAdES-LTV

A3_v3_signed.pdf 24e65f87-feab-4662-b742-9435e432f345
 esborrany -> no firmat
 A3_v2_signat -> signed LTV
 A3_v3_signed.pdf -> signed pades-basic
 marcat com a definitiu -> signed pades-basic
```

Es decir, al subir una versión firmada (se hace resellado), pero si a continuación se vuelve a subir otra versión firmada, a esa versión no se aplica el resellado.

**Comment by CesarGarcia-inetum** [comment]
Hemos estado chequeando este punto. Hemos visto que el comportamiento puede ser que no sea el correcto.

Se puede crear un documento en estado borrador, si se encuentra en estado borrador y pasa a definitivo, este documento (con aspecto "gdib:borrador") se firma si no lo estaba previamente, y pasa a estado definitivo (quitando el aspecto "gdib:borrador"), para ello se chequea que el perfil de firma haya cambiado, y en ese caso se hace el "resellado".

Aquí hay un tema que nos choca, ya que en la prueba que nos indicas, primero subes una versión firmada y hace resellado (hasta aquí correcto), pero luego actualizas el contenido por completo del documento con otra firma completamente diferente, ¿este caso tiene sentido estando en estado definitivo el documento?, aún así, como ya no tiene el aspecto "gdib:borrador", GDIB no comprueba la firma, de ahí que no haga el resellado ni modificación del documento.

Si que es cierto, que cuando se cierra el expediente y lo mueve al RM se chequea la firma de nuevo.

Tenemos que hacer más pruebas de este caso que comentas. Quedamos a tu vuelta para hacer una sesión práctica.

Pero viendo el código hemos visto que hay un error de bulto, ¿por qué siempre se pone el el metadato "eni:fecha_sellado" la fecha a fuego en el código a "new Date(0)"?, esto lo pone siempre a 1 de enero de 1970. ¿No debería ser la fecha en el que se firma el documento?.

```
/**
 * Actualizo la fecha de sellado del nodo con la fecha del sistema
 *
 * @param node
 *            nodo a modificar
 */
public void updateResealDate(Node node) {
		Property property = new Property(ConstantUtils.PROP_FECHA_SELLADO_QNAME, ISO8601DateFormat.format(new Date(0)));
		node.getProperties().add(property);
}

public void updateResealDate(NodeRef node) {
		nodeService.setProperty(node, ConstantUtils.PROP_FECHA_SELLADO_QNAME, ISO8601DateFormat.format(new Date(0)));
}
```

Este metadato es importante, además del que tenemos que añadir para el resellado del metadato "gdib:fecha_validez_certificado" que estamos haciendo con la incidencia #114 para poder a futuro hacer el resellado correctamente.

**Comment by tgaya-dgtic** [comment]
Respecto a la comprobación de resellado, en lugar de hacerse con gdib:borrador, debería comprobarse si el documento que se sube incluye firma. Si incluye firma, siempre debería hacerse la verificación de la firma y el resellado. (Esto aplicará tanto si es un documento borrador con firma, como si es un documento definitivo (firmado)).
(Como comentario aparte, cuando un documento está marcado como definitivo, ya no se permite modificarlo ni subir nuevas versiones).

Sí, entiendo que debería ponerse la fecha actual.

**Comment by CesarGarcia-inetum** [comment]
Hemos comprobado más este tema, y no se hace resellado si no cambia el "Perfil de firma", los posibles perfiles de firma son:

	 * @param signatureFormat Formato de firma tipo ENI ("TF02_#_T", "TF02_#_LTV", etc.).
	 * @return Perfil de firma avanzado eEMGDE ("T", "LTV", "A", etc.).

Un documento sin firma, cuando se modifica (sube nueva versión por ejemplo), se realiza la firma y resellado, cuando un documento está firmado y se sube nueva versión con firma, se comprueba que el perfil de firma haya cambiado, sino no hace el resellado.

Esto se puede cambiar, ya nos dices cuál es la funcionalidad exactamente.

**Comment by tgaya-dgtic** [comment]
Con las pruebas que hice (están en esta misma issue), si tenemos un documento borrador subido como pades-basic, lo convierte a pades-ltv, pero la siguiente vez que lo subo como pades-basic, conserva los metadatos pero no lo convierte a pades-ltv. Por tanto el funcionamiento es incorrecto.

Debería cambiar la funcionalidad:
- en caso definitivo. No es aplicable porque cuando es definitivo no se deben poder modificar ni metadatos ni documento.
- en caso de borrador (puede tener firma o no tenerla).
  - si el nuevo documento no tiene firma, entonces hay que limpiar los metadatos de firma si ya existieran (aspecto firmado... También si es detached, habría que eliminar el stream de la firma).
  - si el nuevo documento tiene firma, entonces se comprueba la firma y según unas tablas que tiene, si no basta, hace upgrade de la firma. Entonces se rellenan los metadatos de firma (o bien con los obtenidos de la comprobación, si son suficientes, o bien con los del upgrade de firma, en el caso de haber realizado el upgrade). Si es un cades detached, tendrá stream adicional para la firma.

Si acaso en la reunión lo hablamos.

**Comment by tgaya-dgtic** [comment]
Si queréis hacer las pruebas vosotros, haced un pull (he hecho un commit hoy)
https://git.caib.es/dgmad-public/exemple_peticions_plugin_arxiu/

y en el fichero config.properties tenéis que poner
idExpedient=
creaExpedient=true
provesEsborranySignatDefinitiu=true
provesImprimible=false
provesXml=false
provesAttached=false
provesDetached=false
tancaExpedient=false

Lo que hace es ir ejecutando cada paso y esperando a que se introduzca Intro para ir al siguiente. Por tanto, desde Alfresco os podéis bajar el documento y por ejemplo en valide validarlo para comprobar el tipo de firma que incluye (básica, sello de tiempo...), que debería coincidir con los metadatos de ese documento en Alfresco.

**Comment by tgaya-dgtic** [comment]
Según lo que comentamos en la reunión de ayer, he vuelto a repetir las pruebas, porque las primeras pruebas que puse en esta incidencia había ficheros que estaban firmados como ltv y deberían estar como básicos.
Por tanto, es cierto lo que decíais de que el 1er paso también lo hace mal, de borrador a definitivo porque no hace upgrade de firma y sin embargo lo pone como pades-ltv.
Además también he añadido los cambios en los metadatos, para ver mejor qué es lo que hace.

```
expedient c17bcbd6-6888-424c-b6ea-4ed074826dbf

document b34a2212-a90f-4ec6-ab07-82ec5c3fb53d
crea esborrany  A3_v1.pdf  no firmado  ->  no firmado

    "cmis:secondaryObjectTypeIds": [
      "P:eni:interoperable",
      "P:eni:transferible",
      "P:cm:titled",
      "P:gdib:borrador",
      "P:sys:localized"
    ],

A3_v2_signed.pdf  pades basico  -->  pades basico

    continúa con los metadatos anteriores, y añade:
    "cmis:secondaryObjectTypeIds": [
      "P:eni:firmadoBase"
    ]
    "eni:csv": null,
    "eni:perfil_firma": "LTV",
    "eni:tipoFirma": "TF06",
    "eni:fecha_sellado": null,
    todo esto es incorrecto pq la firma del documento bajado es pades basico, no ltv

A3_v3_signed.pdf  pades basico  -->  pades basico

    continúa con los mismos metadatos de firma

marcar como definitivo   -->  pades basico

    se elimina este aspecto
    "cmis:secondaryObjectTypeIds": [
      "P:gdib:borrador"
    ]
    se cambian los valores de:
    "eni:csv": "390f24e751b393c369844d4a768fbb0243d2fe11e1ee45e3059c7911f0fcbc02",
    "eni:fecha_sellado": 1684477428504,
```
Adjunto los ficheros de metadatos, después de cada paso, por si queréis mirar las diferencias vosotros mismos:
[pas1.txt](https://github.com/GovernIB/gdib/files/11514168/pas1.txt)
[pas2.txt](https://github.com/GovernIB/gdib/files/11514170/pas2.txt)
[pas3.txt](https://github.com/GovernIB/gdib/files/11514171/pas3.txt)
[pas4.txt](https://github.com/GovernIB/gdib/files/11514172/pas4.txt)

**Comment by tgaya-dgtic** [comment]
Añado lo que ya habíamos hablado, escrito de otra forma, a ver si queda más claro:

```
El cliente nos envía algo (firmado o no, pero lo demás de firma no se tiene en cuenta)

Entonces, tendremos 2 casos:

borrador sin firma
  limpio (no puede tener metadatos firma)

firmado (borrador firmado o definitivo)
  se comprueba la firma, se hace upgrade de firma (si te pasan un basico lo pasas ltv), y se añaden metadatos firma. (El único caso que no se comprueba es el tipo TF01 CSV)
```

**Comment by tgaya-dgtic** [comment]
Comentado en la reunión de hoy:

    "eni:perfil_firma": "LTV", -> verify @firma  -> qué tipo es < LTV -> upgrade @firma -> contenido + metadatos (incluye firma)
    "eni:tipoFirma": "TF06",   -> tipo de firma: "null", pades (TF06), xades, cades
    "eni:fecha_sellado": null, -> fecha actual en el momento del upgrade o del verify
    "eni:csv": null, -> si definitivo

**Comment by tgaya-dgtic** [comment]
Para tenerlo todo agrupado, añado el email que os envié ayer por la noche:

Si no tiene firma (no tiene "eni:tipoFirma"), se debería subir sin firma y se deberían eliminar los metadatos de la firma que existan.
Si tiene firma (tiene "eni:tipoFirma") y es al comprobar la firma es inválida, entonces se debería devolver un mensaje de error de firma inválida y no se debería hacer ningún cambio al documento.

Y el de esta mañana:

Yo creo que de "eni:tipoFirma" tenemos que fiarnos. Si no está, suponemos que no está firmado. Y si está, pues está firmado y habrá que actuar conforme a este tipo de firma (por ejemplo TF04 es cades detached, es decir, tiene 2 streams, el de contenido y el de firma. En TF01 CSV no hay stream. Y en el resto, hay 1 stream de contenido incluyendo firma).

En cambio, de "eni:perfil_firma" no tenemos por qué fiarnos, primero porque total vamos a enviar el documento a @firma a verificarlo y sabremos la firma que tiene, y segundo porque si es necesario haremos un upgrade de firma por lo tanto ya le habremos cambiado el perfil de firma.

En el caso concreto de que nos envíen un "eni:tipoFirma" (firmado) y luego al hacer la comprobación de "eni:perfil_firma" nos da error la comprobación con @firma (porque no está firmado o la firma no es válida), se envía un mensaje de error al cliente y no se actualiza el documento.

**Comment by CesarGarcia-inetum** [comment]
Hemos hecho una batería de pruebas. Parece que están todos los casos cubiertos.
En caso de que se haya modificado un documento que previamente estaba como PADES LTV y luego se modifica con otro sin firma, se quita todas las propiedades y aspecto de firma que hubiese anteriormente en el nodo original.
Ya nos cuentas en tus pruebas. Está desplegado ya en desarrollo, no hace falta que lo vuelvas a desplegar @tgaya-dgtic .

**Comment by tgaya-dgtic** [comment]
No había tenido tiempo de probar nada, pero ahora le he estado echando una ojeada, y no lo hace bien. Ejemplo:
https://git.caib.es/dgmad-public/exemple_peticions_plugin_arxiu/-/blob/main/src/main/java/client/ArxiuCaibClient.java#L800
Esto añade un documento con firma pades-basic y no se hace upgrade de firma a LTV. Como os comenté aquí https://github.com/GovernIB/gdib/issues/115#issuecomment-1571648852 , debería haberse hecho upgrade a LTV.

**Comment by tgaya-dgtic** [comment]
En la reunión técnica del lunes pasado, les mostré cómo verificar documentos cades (attached y detached).
Quedamos que harían las mismas modificaciones al método crear documento que ya han hecho al modificar documento, y también solamente modificar la fecha de sellado en caso de que se haga upgrade del documento.

**Comment by CesarGarcia-inetum** [comment]
Se añade la lógica en crearDocument (como en el modificarDocument), para que en caso que no sea definitivo (borrador), si el documento está firmado chequee el upgrade de firma.
Está desplegado en el entorno de DES.

**Comment by CesarGarcia-inetum** [comment]
Se añade nueva propiedad "gdib.check.upgradeSign" en gdib-amp.properties, para permitir que se haga Upgrade de @Firma o no. Posibles valores "true" o "false".
Se verifica en la salida que se haya hecho un Upgrade de @Firma en el método "CheckDocumentSignature" y así actualizar o no la "fecha_sellado" de la firma del documento "creado" o "modificado" (modificación o hacerse definitivo).

**Comment by CesarGarcia-inetum** [comment]
Toni, estoy desplegando lo último que hemos hablado esta mañana y me está dando un error intentando invocar al servicio de firma, creo que es un problema temporal con el servicio de firma, ¿no?

```
Caused by: es.caib.gdib.ws.exception.GdibException: No se obtuvo respuesta en la invocación del servicio DSSAfirmaVerify de la plataforma firma para validar una firma electrónica.
        at es.caib.gdib.ws.impl.AfirmaV6SignatureServiceImpl.verifySignature(AfirmaV6SignatureServiceImpl.java:312)
        at es.caib.gdib.ws.impl.RepositoryServiceSoapPortImpl.checkDocumentSignature(RepositoryServiceSoapPortImpl.java:749)
        at es.caib.gdib.ws.impl.RepositoryServiceSoapPortImpl.modifyNode(RepositoryServiceSoapPortImpl.java:1523)
        at es.caib.gdib.ws.impl.authtrans.AuthTransRepositoryServiceSoapPortImpl$3.execute(AuthTransRepositoryServiceSoapPortImpl.java:119)
        at es.caib.gdib.ws.impl.authtrans.AuthTransRepositoryServiceSoapPortImpl$3.execute(AuthTransRepositoryServiceSoapPortImpl.java:115)
        at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:450)

```

**Comment by tgaya-dgtic** [comment]
Efectivamente, hay problemas con el @firma federado del entorno DES y SE.
Cuando funcione os aviso.

**Comment by tgaya-dgtic** [comment]
@firma DES ya funciona.

**Comment by tgaya-dgtic** [comment]
Configuración a añadir en el gdib-amp.properties, para que de momento tenga el mismo comportamiento que antes

```
# Realizar Upgrade de Firma en los documentos borradores firmados (en los documentos definitivos se hace upgrade siempre)
gdib.check.upgradeSign=false
```

Hechas pruebas, parece que va bien.
