### ISSUE TITLE
Error AMP invoices

### ISSUE THREAD

**Issue by tgaya-dgtic** [GovernIB/gdib#116]
El amp de invoices no está funcionando correctamente, en el log la gente de Alfresco ve esto

En sap llaman a este servicio

`    https://doc.caib.es/alfresco/webservice/caib`

    y el servicio es updateMetadata

```
    03.04.2023 13:09:49 El job ha sido lanzado.
    03.04.2023 13:09:49 Paso 001 iniciado (programa ZFACE_MIGR
    03.04.2023 13:09:58 El job ha sido terminado.
```
	
Y les da un error

`    <SAP:AdditionalText>com.sap.engine.interfaces.messaging.api.exception.MessagingException: SOAP: Response message contains an errorXIAdapter/HTTP/ADAPTER.HTTP_EXCEPTION - HTTP 500 500</SAP:AdditionalText>`

En los logs del balanceador yo veo las llamadas

```
10.215.5.147 - - [03/Apr/2023:13:09:51 +0200] "POST /alfresco/webservice/caib HTTP/1.0" 500 575
[03/Apr/2023:13:09:52 +0200] 10.215.5.147 TLSv1.2 ECDHE-RSA-AES128-GCM-SHA256 "POST /alfresco/webservice/caib HTTP/1.0" 574 "jvm1" 4086 0
```

Y luego en el nodo de alfresco veo lo siguiente

```
    2023-04-03 13:09:52,297 DEBUG [dao.impl.WSAuditDaoImpl] [auditTaskExecutor-3482] Insert Done.
    2023-04-03 13:09:52,299 DEBUG [dao.impl.WSAuditDaoImpl] [auditTaskExecutor-3636] Insert Done.
    Apr 03, 2023 1:09:52 PM javax.xml.soap.FactoryFinder find
    WARNING: Using deprecated META-INF/services mechanism with non-standard property: javax.xml.soap.MetaFactory. Property javax.xml.soap.SAAJMetaFactory should be used instead.
    2023-04-03 13:09:52,361 DEBUG [dao.impl.WSAuditDaoImpl] [auditTaskExecutor-3661] Insert Done.
    Apr 03, 2023 1:09:52 PM javax.xml.soap.FactoryFinder find
    WARNING: Using deprecated META-INF/services mechanism with non-standard property: javax.xml.soap.MetaFactory. Property javax.xml.soap.SAAJMetaFactory should be used instead.
    2023-04-03 13:09:52,605 DEBUG [dao.impl.WSAuditDaoImpl] [auditTaskExecutor-3658] Insert Done.
    [Fatal Error] :1:1: Content is not allowed in prolog.

    2023-04-03 13:09:52,910 DEBUG [ws.handlers.AlfrescoAuthHandler] [ajp-nio-0.0.0.0-8009-exec-298] Enter - inboundProperty!!
    Apr 03, 2023 1:09:52 PM javax.xml.soap.FactoryFinder find
    WARNING: Using deprecated META-INF/services mechanism with non-standard property: javax.xml.soap.MetaFactory. Property javax.xml.soap.SAAJMetaFactory should be used instead.
    2023-04-03 13:09:52,912 DEBUG [ws.handlers.AlfrescoAuthHandler] [ajp-nio-0.0.0.0-8009-exec-298] Enter - close!!
    2023-04-03 13:09:52,991 DEBUG [dao.impl.WSAuditDaoImpl] [auditTaskExecutor-3626] Insert Done.
    Apr 03, 2023 1:09:53 PM javax.xml.soap.FactoryFinder find
    WARNING: Using deprecated META-INF/services mechanism with non-standard property: javax.xml.soap.MetaFactory. Property javax.xml.soap.SAAJMetaFactory should be used instead.
    2023-04-03 13:09:53,238 DEBUG [dao.impl.WSAuditDaoImpl] [auditTaskExecutor-3662] Insert Done.
    Apr 03, 2023 1:09:53 PM javax.xml.soap.FactoryFinder find
    WARNING: Using deprecated META-INF/services mechanism with non-standard property: javax.xml.soap.MetaFactory. Property javax.xml.soap.SAAJMetaFactory should be used instead.
    2023-04-03 13:09:53,318 DEBUG [dao.impl.WSAuditDaoImpl] [auditTaskExecutor-3668] Insert Done.
    Apr 03, 2023 1:09:53 PM javax.xml.soap.FactoryFinder find
    WARNING: Using deprecated META-INF/services mechanism with non-standard property: javax.xml.soap.MetaFactory. Property javax.xml.soap.SAAJMetaFactory should be used instead.
    2023-04-03 13:09:53,725 DEBUG [dao.impl.WSAuditDaoImpl] [auditTaskExecutor-3602] Insert Done.
    2023-04-03 13:09:53,739 DEBUG [dao.impl.WSAuditDaoImpl] [auditTaskExecutor-3669] Insert Done.
    Apr 03, 2023 1:09:53 PM javax.xml.soap.FactoryFinder find
    WARNING: Using deprecated META-INF/services mechanism with non-standard property: javax.xml.soap.MetaFactory. Property javax.xml.soap.SAAJMetaFactory should be used instead.
    Apr 03, 2023 1:09:53 PM javax.xml.soap.FactoryFinder find
    WARNING: Using deprecated META-INF/services mechanism with non-standard property: javax.xml.soap.MetaFactory. Property javax.xml.soap.SAAJMetaFactory should be used instead.
    2023-04-03 13:09:53,952 DEBUG [dao.impl.WSAuditDaoImpl] [auditTaskExecutor-3670] Insert Done.
    2023-04-03 13:09:53,960 DEBUG [dao.impl.WSAuditDaoImpl] [auditTaskExecutor-3597] Insert Done.
    Apr 03, 2023 1:09:53 PM javax.xml.soap.FactoryFinder find
    WARNING: Using deprecated META-INF/services mechanism with non-standard property: javax.xml.soap.MetaFactory. Property javax.xml.soap.SAAJMetaFactory should be used instead.
    2023-04-03 13:09:54,021 DEBUG [dao.impl.WSAuditDaoImpl] [auditTaskExecutor-3671] Insert Done.
    Apr 03, 2023 1:09:54 PM javax.xml.soap.FactoryFinder find
    WARNING: Using deprecated META-INF/services mechanism with non-standard property: javax.xml.soap.MetaFactory. Property javax.xml.soap.SAAJMetaFactory should be used instead.
    Apr 03, 2023 1:09:54 PM javax.xml.soap.FactoryFinder find
    WARNING: Using deprecated META-INF/services mechanism with non-standard property: javax.xml.soap.MetaFactory. Property javax.xml.soap.SAAJMetaFactory should be used instead.
    2023-04-03 13:09:54,454 DEBUG [dao.impl.WSAuditDaoImpl] [auditTaskExecutor-3650] Insert Done.
    2023-04-03 13:09:54,852 DEBUG [dao.impl.WSAuditDaoImpl] [auditTaskExecutor-3640] Insert Done.

    13:31:23

    2023-04-03 13:10:11,227 DEBUG [dao.impl.WSAuditDaoImpl] [auditTaskExecutor-3633] Insert Done.
    Apr 03, 2023 1:10:11 PM javax.xml.soap.FactoryFinder find
    WARNING: Using deprecated META-INF/services mechanism with non-standard property: javax.xml.soap.MetaFactory. Property javax.xml.soap.SAAJMetaFactory should be used instead.
    2023-04-03 13:10:11,744 DEBUG [dao.impl.WSAuditDaoImpl] [auditTaskExecutor-3660] Insert Done.
    Apr 03, 2023 1:10:11 PM javax.xml.soap.FactoryFinder find
    WARNING: Using deprecated META-INF/services mechanism with non-standard property: javax.xml.soap.MetaFactory. Property javax.xml.soap.SAAJMetaFactory should be used instead.
    2023-04-03 13:10:11,874 DEBUG [dao.impl.WSAuditDaoImpl] [auditTaskExecutor-3672] Insert Done.
    Apr 03, 2023 1:10:12 PM javax.xml.soap.FactoryFinder find
    WARNING: Using deprecated META-INF/services mechanism with non-standard property: javax.xml.soap.MetaFactory. Property javax.xml.soap.SAAJMetaFactory should be used instead.
    2023-04-03 13:10:12,557 DEBUG [dao.impl.WSAuditDaoImpl] [auditTaskExecutor-3673] Insert Done.
    Apr 03, 2023 1:10:12 PM javax.xml.soap.FactoryFinder find
    WARNING: Using deprecated META-INF/services mechanism with non-standard property: javax.xml.soap.MetaFactory. Property javax.xml.soap.SAAJMetaFactory should be used instead.
    2023-04-03 13:10:13,016 DEBUG [dao.impl.WSAuditDaoImpl] [auditTaskExecutor-3674] Insert Done.
    Apr 03, 2023 1:10:13 PM javax.xml.soap.FactoryFinder find
    WARNING: Using deprecated META-INF/services mechanism with non-standard property: javax.xml.soap.MetaFactory. Property javax.xml.soap.SAAJMetaFactory should be used instead.
    2023-04-03 13:10:13,167 DEBUG [dao.impl.WSAuditDaoImpl] [auditTaskExecutor-3482] Insert Done.
    Apr 03, 2023 1:10:14 PM javax.xml.soap.FactoryFinder find
    WARNING: Using deprecated META-INF/services mechanism with non-standard property: javax.xml.soap.MetaFactory. Property javax.xml.soap.SAAJMetaFactory should be used instead.
    Apr 03, 2023 1:10:14 PM javax.xml.soap.FactoryFinder find
    WARNING: Using deprecated META-INF/services mechanism with non-standard property: javax.xml.soap.MetaFactory. Property javax.xml.soap.SAAJMetaFactory should be used instead.
    2023-04-03 13:10:14,242 DEBUG [dao.impl.WSAuditDaoImpl] [auditTaskExecutor-3636] Insert Done.
    2023-04-03 13:10:14,394 DEBUG [dao.impl.WSAuditDaoImpl] [auditTaskExecutor-3661] Insert Done.
    Apr 03, 2023 1:10:14 PM javax.xml.soap.FactoryFinder find
    WARNING: Using deprecated META-INF/services mechanism with non-standard property: javax.xml.soap.MetaFactory. Property javax.xml.soap.SAAJMetaFactory should be used instead.
    2023-04-03 13:10:14,699 DEBUG [dao.impl.WSAuditDaoImpl] [auditTaskExecutor-3658] Insert Done.
    Apr 03, 2023 1:10:14 PM javax.xml.soap.FactoryFinder find
    WARNING: Using deprecated META-INF/services mechanism with non-standard property: javax.xml.soap.MetaFactory. Property javax.xml.soap.SAAJMetaFactory should be used instead
```

**Comment by tgaya-dgtic** [comment]
Los de SAP comentan:

En principio, aunque ponga un warning el problema debe venir por el mensaje que indica de:
Using deprecated META-INF/services mechanism with non-standard property: javax.xml.soap.MetaFactory. Property javax.xml.soap.SAAJMetaFactory should be used instead.

Hay foros y referencias respecto a este error:
https://es.stackoverflow.com/questions/112201/error-in-glassfish-5-using-deprecated-meta-inf-services-property-javax-xml-soa
https://github.com/javaee/metro-jax-ws/issues/1237

**Comment by CarlosDiez-inetum** [comment]
El pom.xml tiene pinta de haber sido modificado a mano. No ha sido refactorizado correctamente usando SDK 4 de Alfresco.
El ws busca un contenido con la propiedad connexasArchivelink:sapid X y luego actualiza otras propiedades del modelo invoices-model.xml a través de los parámetros que envía.

El contenido se encuentra en la ruta del repositorio: /app:company_home/cm:connexas/cm:Facturas/cm:DC/

Se crea cliente SOAP de pruebas contra el entorno de desarrollo: 
[pruebas-caib.zip](https://github.com/GovernIB/gdib/files/11158024/pruebas-caib.zip)

**Comment by CarlosDiez-inetum** [comment]
Ejemplo de petición al WS de Invoices:
[ejemplo_peticion_invoices_ws.txt](https://github.com/GovernIB/gdib/files/11158053/ejemplo_peticion_invoices_ws.txt)

**Comment by tgaya-dgtic** [comment]
He hablado con los de SAP y en principio como que si lo cambiamos a REST ellos también lo tendrán que reimplementar y alguien lo tendrá que pagar, prefieren que se continue con SOAP y si la dependencia está deprecada, se solucione poniendo otra versión de la librería.

**Comment by tgaya-dgtic** [comment]
Esta mañana hemos hablado de pasar el servicio de SOAP a REST.
Los de SAP dan el visto bueno, pero indican "pueden proceder con el cambio en el servicio en Alfresco y lo cambien a tipo REST pero el mensaje tiene que ser XML no JSON.
De esta forma en el sistema SAP PI se puede aprovechar el mapeo existente y minimizar el esfuerzo de modificaciones."

**Comment by CarlosDiez-inetum** [comment]
He subido el módulo de invoices migrado correctamente con el SDK 4.1 de Alfresco y el cambio para pasar el WS de SOAP a REST. Está subido en una nueva rama 'invoices-dev-issue-116'.

Por favor, ¿podrías probar a desplegarlo en DEV? @tgaya-dgtic 

Además, durante la migración, he visto que insertan propiedades huérfanas. Es decir, que ya no existen en el modelo documental de invoices. Estas propiedades se reciben por el WS y se insertan igualmente. Habría que revisar funcionalmente esto.

**Comment by tgaya-dgtic** [comment]
Compilado y desplegado en el servidor 9.
Parece que peta y no es capaz de cargar la licencia de alfresco. Échale una ojeada al log.

Crea un documento detallando los problemas del modelo documental, y se lo pasaremos a la gente de Sap.

**Comment by CarlosDiez-inetum** [comment]
El error se produce porque detecta cambios en la versión del artefacto y no deja desplegarlo con la misma versión del pom '1.5.1-SNAPSHOT' que ya tenía desplegada: 

Downgrading of modules is not supported.
Module 'invoices' version 1.5.1 is currently installed and must be uninstalled before version 1.5.1-SNAPSHOT can be installed.
        at org.alfresco.error.AlfrescoRuntimeException.create(AlfrescoRuntimeException.java:52)
        at org.alfresco.repo.module.ModuleComponentHelper.startModule(ModuleComponentHelper.java:633)
        at org.alfresco.repo.module.ModuleComponentHelper.access$5(ModuleComponentHelper.java:530)
        at org.alfresco.repo.module.ModuleComponentHelper$1$1.execute(ModuleComponentHelper.java:263)
        at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:450)
        at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:338)
        at org.alfresco.repo.module.ModuleComponentHelper$1.doWork(ModuleComponentHelper.java:284)
        ... 46 more

Subo un cambio en pom para ir a la microversión 1.5.1.1. Por favor, ¿podemos dejar desplegada la rama 1.5.0.1 para las pruebas del WSO2? Después de eso, nos metemos con el despliegue de invoices. Para no bloquear a nadie.

**Comment by CarlosDiez-inetum** [comment]
He subido varios commits a la nueva rama corrigiendo un error tipográfico en la query FTS y añadiendo las propiedades al modelo y trazas. Por favor, ¿podríamos desplegarlo @tgaya-dgtic?

Una vez validado el funcionamiento, subiremos la colección de Postman con la llamada

**Comment by tgaya-dgtic** [comment]
Hecho pull, compilado y desplegado.

**Comment by CarlosDiez-inetum** [comment]
Añadidas trazas de log a nivel INFO y validado el funcionamiento en desarrollo. Ahora falta que lo prueben los de SAP.
@tgaya-dgtic, adjunto la colección con la petición. 

Como aclaración, el documento se busca en Alfresco mediante la propiedad 'arcDocId' que corresponde en ACS a la propiedad 'connexasArchivelink:sapid' de los archivos subidos mediante el conector de SAP.

[CAIB - Invoices.postman_collection.json.zip](https://github.com/GovernIB/gdib/files/11551935/CAIB.-.Invoices.postman_collection.json.zip)

**Comment by tgaya-dgtic** [comment]
Ayer lo desplegué en DES (nuestro propio entorno) y pasé la información a los de SAP para que prueben.

**Comment by tgaya-dgtic** [comment]
La gente de SAP me piden la documentación de la integración REST.

**Comment by CesarGarcia-inetum** [comment]
Adjuntamos el documento de integración Rest del nuevo servicio.

[Integración Invoices GDIB.pdf](https://github.com/GovernIB/gdib/files/11602265/Integracion.Invoices.GDIB.pdf)

**Comment by tgaya-dgtic** [comment]
Entregada nueva documentación a la gente de SAP, para que den el ok o propongan cambios.

**Comment by CarlosDiez-inetum** [comment]
En fase de pruebas con el equipo de SAP

**Comment by CarlosDiez-inetum** [comment]
Buenos días, @tgaya-dgtic .

Estábamos realizando pruebas de invoices y al lanzar los clientes HTTP recibimos un 503 con el siguiente cuerpo:
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html>

<head>
	<title>503 Service Temporarily Unavailable</title>
</head>

<body>
	<h1>Service Temporarily Unavailable</h1>
	<p>The server is temporarily unable to service your
		request due to maintenance downtime or capacity
		problems. Please try again later.</p>
	<hr>
	<address>Apache/2.2.15 (Red Hat) Server at docdes2.caib.es Port 443</address>
</body>

</html>

Por favor, ¿podríais echarle un ojo?

Un saludo.

**Comment by tgaya-dgtic** [comment]
No me han dicho nada.
Podéis volver a probar ahora, veo que ya está disponible.

**Comment by CarlosDiez-inetum** [comment]
Ya está funcionando de nuevo. Gracias.
Seguimos con las pruebas de integración.

**Comment by tgaya-dgtic** [comment]
Todavía está pendiente de las pruebas...

**Comment by CarlosDiez-inetum** [comment]
Está en lado del equipo de SAP. Nosotros hemos terminado las pruebas técnicas con ellos y todo era OK. 

Deben de tener un proceso distinto para desplegar en su lado, porque me han comentado que está el equipo funcional de SAP con ello. Por favor, preguntadles porque eso debe significar que ya lo tienen desplegado en vuestro entorno de TEST.

**Comment by tgaya-dgtic** [comment]
Parece que la gente de SAP no tiene forma de verificar el buen funcionamiento en el entorno DES.
He compilado la rama de esta issue 116 y he pedido (incidencia interna) que lo desplieguen en el entorno SE.

**Comment by CarlosDiez-inetum** [comment]
Ok. Con sustituir el AMP de invoices por el nuevo debería ser suficiente. Además, en la consola de Alfresco podemos ver si está el microversionado que hemos añadido, como comprobación.

**Comment by tgaya-dgtic** [comment]
Parece que se quejan los de SAP porque el campo serialNumber actualmente es obligatorio y parece ser que debería ser opcional. Les da este error `"Error 400: Error de validación Fallos de validaciÃ³n: 'serialNumber' is null or empty".`
Se puede modificar para que sea opcional?

**Comment by CesarGarcia-inetum** [comment]
Buenos días Toni,

Lo miramos y os decimos.


Saludos,



Inetum



César Alberto García Cruz
Alfresco Team Leader | Intelligent Information Management



+34 650 64 59 21


María de Portugal, 9-11 Edificio 1

28050 Madrid (España)


inetum.com <https://www.inetum.com/>

Facebook<https://www.facebook.com/inetum.world> / Twitter<https://twitter.com/inetum_world> / LinkedIn<https://www.linkedin.com/company/inetum> / Instagram<https://www.instagram.com/inetum_world/> / YouTube<https://www.youtube.com/c/Inetum>

[cid:734bbbb8-43d0-46b8-9fd7-91567296f5a1]<https://www.inetum.com/es>
Piensa en verde, consérvalo en tu pantalla. Este mensaje y sus archivos adjuntos están destinados únicamente a los destinatarios previstos y son confidenciales. Si recibe este mensaje por error, elimínelo, así como las posibles copias en sus sistemas, y notifique inmediatamente al remitente.
Se prohíbe cualquier vista no autorizada, uso que no cumpla con su finalidad, difusión o divulgación, ya sea total o parcial.

________________________________
De: ToniG ***@***.***>
Enviado: martes, 11 de julio de 2023 13:51
Para: GovernIB/gdib ***@***.***>
Cc: Garcia-Cruz Cesar ***@***.***>; Assign ***@***.***>
Asunto: Re: [GovernIB/gdib] Error AMP invoices (Issue #116)


Parece que se quejan los de SAP porque el campo serialNumber actualmente es obligatorio y parece ser que debería ser opcional. Les da este error "Error 400: Error de validación Fallos de validaciÃ³n: 'serialNumber' is null or empty".
Se puede modificar para que sea opcional?

**Comment by CesarGarcia-inetum** [comment]
Ya permite que el campo "serialNumber" no sea obligatorio en la llamada desde SAP.
He subido los cambios en el Git para desarrollo.

```
{
    "arcDocId":"596C4BE72E6EDDE2E10080030AD7059B",
    "invoiceNumber":"141",
    "providerId":"A07009574",
    "providerName":"AGRUPACION MEDICA BALEAR. S.A.",
    "issueDate":"2022-12-30T20:00:00.000+01:00",
    "invoiceTotal":"3342.00",
    "dir3":"A04005006",
    "docid":"596C4BD62E6EDDE2E10080030AD7059B",
    "archivid":"DC"
}
```

```
{
    "status": {
        "code": 200,
        "name": "OK",
        "description": "The request succeeded normally."
    },
    "message": "OK",
    "exception": "",
    "callstack": [],
    "server": "Enterprise v6.2.2 (r52ea53ca-b2978) schema 13,005",
    "time": "Jul 13, 2023, 2:36:45 PM"
}
```

**Comment by tgaya-dgtic** [comment]
Parece que le va bien. Pasamos a PRO y cierro incidencia.
