### ISSUE TITLE
Millorar error si el format d'una data es incorrecte en busquedaFacilExpedientes()

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/gdib#13]
Una cosa, per provar que no feia cas del finalDate tenia una data final de proves "2018-05-08T10:15:00.000+0200 sdgfsdgf" que una vegada executat l'exemple m'ha llançat el següent error incomprensible. Estaria bé si hi ha temps, que un error de format de dates llanci un error més comprensible:

**java.lang.Exception:  Error Consultant si Expedient existeix: COD_021-041415389 Request  failed 400  /solr4/alfresco/alfresco?wt=json&fl=DBID%2Cscore&rows=1000&df=TEXT&start=0&locale=en_US&alternativeDic=DEFAULT_DICTIONARY&fq=%7B%21afts%7DAUTHORITY_FILTER_FROM_JSON&fq=%7B%21afts%7DTENANT_FILTER_FROM_JSON&fq=%7B%21afts%7D%7Bhttp%3A%2F%2Fwww.alfresco.org%2Fmodel%2Fsecuritymarks%2F1.0%7Dclassification%3A%22U%22+OR+-ASPECT%3A%7Bhttp%3A%2F%2Fwww.alfresco.org%2Fmodel%2Fclassifiedcontent%2F1.0%7Dclassified**

**Comment by dsariego-memorandum** [comment]
Tras revisar el bus, se observa que en todos los servicios se trata igual las excepciones, y es que siempre que algún método devuelva una excepción, en vez de mostrar esta, se cambia por el 'COD_021'. Hacer los cambios en el método que atañe a esta incidencia y todos los demás llevaría muchísimas horas de desarrollo, por lo que, con lo commiteado anteriormente consideramos solucionada la incidencia, ya que manda una GdibException controlada con un formato fijo, y también sale esta reflejada en los logs claramente.

**Comment by atrobat-dgtic** [comment]
Como solución intermedia, i como comentamos en la reunión, se podria hacer que el bus lance el mensaje que devueve GDIB a las aplicaciones, de esta manera la aplicación final tiene visibilidad de lo que está pasando.

**Comment by dsariego-memorandum** [comment]
Se ha controlado el caso para que se muestre al usuario:
"
{"searchDocumentsResult": {"result": {
   "code": "COD_020",
   "description": "La consulta lucene contiene errores de sintaxis."
}}}
"

Cuando se produce un error de sintaxis en la construcción de la consulta lucene
