### ISSUE TITLE
Errors no controlats a causa de suposats errors en la TSA (segell de temps)

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/gdib#14]
Duplicat a https://github.com/GovernIB/pluginsib/issues/52

Pareix ser que quan hi ha errors durant el Segellat de Temps en @firma federat, l'arxiu no sap gestionar correctament aquests errors i llança un error no controlat. Despres de passar per l'ESB ja la cosa arriba feta una "coca" i en DocCustodyArxiuCAIB és llança una Excepció sense donar oportunitat a reintents.
Afegir try-catch a les operacions de finalizarDocumento() i cerrarExpediente() i si s'ajusta a un error de TSA llavors forçar reintents.

Podeu veure les traces d'error obtingudes a  https://github.com/GovernIB/pluginsib/issues/52

**Comment by cbernus-memorandum** [comment]
Actualmente las excepciones relativas a los errores provenientes del servidor de @firma se encuentran controladas en el archivo AfirmaV6SignatureServiceImpl , las peticiones al servidor de firma se lanzan mediante el uso de las librerías Integra y estas solamente devuelven errores con estos códigos, tal como están configuradas ahora mismo las librerías de Integra ( esto es, que el servidor federado se encarga de las peticiones a la TSA y no se hacen directamente ) 
![image](https://user-images.githubusercontent.com/61832001/96564385-62c60780-12c3-11eb-8227-1e5dfa92cfe6.png)
Por lo que actualmente, identificar un error proveniente de la TSA no sería "fácil" debido a no poder clasificarlo por el Tipo de error devuelto. 
Aun así, si todavia sigue ocurriendo este error sería de ayuda recibir una muestra de los logs, ya que actualmente en el entorno de desarrollo no he sido capaz de reproducirlo. 
En el manual de las librerías integra, en el documento de cambios y novedades de la versión 2.2.1 han aparecido varios errores resueltos que corregían problemas provenientes del parseo de sellos de tiempo y referentes a la TSA, por lo que quizá fuera un error resuelto.
De todas formas si todavía quereís que modifique las peticiones de GDIB que se encargan de hacer las peticiones de integra, hay que tener en cuenta que al no poder identificar estos errores únicamente (  los referidos a la TSA ), generaremos cierta  sobrecarga de peticiones respecto al volumen actual ya que se generarían varias peticiones ( el número de reintentos debería ser acotado o proveniente de un fichero properties como el gdib-amp.properties por ejemplo ) siempre que estas peticiones de firma fallen, es decir incluso cuando ocurra que una firma no sea válida, aumentará el tiempo de respuesta al reintentar validar una firma no válida, pero en todas las peticiones de firma, ralentizando los tiempos de respuesta.

**Comment by atrobat-dgtic** [comment]
Carlos, creo que el problema viene que cuando hay errores en la TSA, se generan errores tipo readSocketTimeOut o connectionTimeOut y no sé como los devuelve @firma.  De hecho a veces pasa que la petición acaba sin respuesta del archivo a la aplicaión. Creo que lo que se debería controlar es que si por lo que sea, @firma no contesta, que gdib de algún tipo de respueta a la aplicación.

**Comment by cbernus-memorandum** [comment]
La cuestión es que desde las librerías integra ya está gestionando eso, suele catchear las excepciones que le deben de poder dar y las devuelve formando mensajes como los que he adjuntado en la imagen de manera estándar a la librería cliente. 
[Aquí ](https://github.com/ctt-gob-es/integra/blob/5cb13636313b2d6453a9b4c21c27812936968757/Integra-parent/Integra-ws/src/main/java/es/gob/afirma/wsServiceInvoker/Afirma5ServiceInvokerFacade.java#L189
)podemos observar como todas las llamadas de invocar servicio están controladas con try and catch, por eso me extraña que aunque la TSA falle, no devuelva mensaje de error vaya, y si devuelve mensaje de error, GDIB ya está controlando la validez del resultado de las operaciones de firma.

De todas formas, hay alguna manera de reproducir el error de manera fija? desconfigurando la TSA por ejemplo desde la consola de @firma y probar?

**Comment by atrobat-dgtic** [comment]
Se lo podriamos pedir a Cristina, que desconfigure la TSA de @firma que utiliza vuestro entorno de desarrollo.  Cuando lo querais probar hablamos la avisamos.

**Comment by cbernus-memorandum** [comment]
Nah eso no servirá por que devuelve mensaje de error @Firma, durante la migración ya nos pasó al configurar la aplicación de firma nueva para la máquina 4, que no estaba la TSA configurada, y devuelve mensaje de error estándar y en la descripción dice que hubo un problema con el sello de tiempo. Como comentamos en la reunión tendremos que analizar para hacer un sistema para ejecutar las operaciones críticas de firma de manera asíncrona para no bloquear el sistema y añadir el sistema de reintentos ahí

**Comment by tgaya-dgtic** [comment]
Continua a la incidència #46
