### ISSUE TITLE
Actualización gdib para Alfresco 6.2

### ISSUE THREAD

**Issue by tgaya-dgtic** [GovernIB/gdib#17]
Completar la compilación de gdib para Alfresco 6.2 (Evidentemente los módulos deben compilar y crear la estructura correcta del paquete que se desplegará en Alfresco)
La comprobación correcta de esta tarea se realizará:
· Con las pruebas básicas del Pbae.
· Con las pruebas exhaustivas del Soapui (Habrá que editar algunas pruebas para cambiar identificadores de documento que ya no existen en Alfresco por unos de documentos actuales).
· Ejecución de Cronjobs
· Interfaz en el share para la edición de funciones y series.

(Tarea importada desde Redmine)

**Comment by tgaya-dgtic** [comment]
En principio está realizado.
Pendiente de realizar más pruebas una vez que estén los ficheros desplegables de gdib definitivos.

**Comment by tgaya-dgtic** [comment]
Falta subir las subcarpetas Integra-parent\documentacion e Integra-parent\Integra-services.
Si no, no compila.

**Comment by cbernus-memorandum** [comment]
Subi la carpeta de Integra-parent para no subir una carpeta por cada una y necesitan el pom parent para las dependencias, pero compilar las compilo individualmente cada una de ellas.

**Comment by cbernus-memorandum** [comment]
Ya los he subido, de todas formas como comento, yo compilo cada .jar de manera individual
Un saludo!

**Comment by tgaya-dgtic** [comment]
El darrer missatge no té res a veure amb la branca 1.5 (és relatiu a la branca 2, que s'integra amb Archium-Gdib).
