### ISSUE TITLE
No es retorna el mimetype del document ni la firma quan no es demana el contingut

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/gdib#2]
Obtenir el Document però descarregant el binari (apiArxiu.obtenerDocumento(idDocument, true); ) i si que retorna el MIME. Quan deman informació del document sense descàrrega de binari (apiArxiu.obtenerDocumento(idDocument, false); ) , llavors el MIME val null. 

fer que GDIB retorni el mimetype en els dos casos

**Comment by dsariego-memorandum** [comment]
Debido a que se trata de cambios en el mismo sitio para las incidencias #2 y #3, estas se han commiteado juntas.
Con estos cambios GDIB devolverá, siempre que se trate de un documento, información sobre el contenido del documento aunque este no se obtenga (tamaño del contenido, mimetype...).
Además, también se añaden cambios en el cliente jersey que serían necesarios para recoger este valor. Falta en este commit los cambios en el bus, los cuales se envían por correo, como nos pedisteis

**Comment by dsariego-memorandum** [comment]
Se commitean los cambios para las incidencias #2 y #3 juntas, en este commit se añaden unos cambios que faltaban cuando se intenta obtener un documento migrado, además, se arregla un error no reportado que había cuando el booleano de obtener contenido se ponía a false obteniendo estos documentos migrados, y los cambios en los archivos del esb necesarios para que muestre al exterior los nuevos datos.

Debido a que en una de las incidencias se pedía recuperar datos del mimeType aunque se pusiese a false el booleano de obtener el contenido, y la otra incidencia trataba de añadir un nuevo booleano de información del contenido, he aplicado la misma lógica para ambos atributos, para que se muestren siempre se desee recuperar el contenido o no (he comprobado que esto no afecta al tiempo de respuesta de la petición). Si no se quiere que se devuelva el tamaño de la firma cuando el booleano de obtener contenido sea false, decidmelo y haré otro nuevo commit cambiando esto (son unos cambios fáciles que no llevaría más de media hora hacer y probarlos)

En cuanto a los cambios del bus, como he dicho, están incluídos en este commit, se trata de unos cambios sobre la forma de tratar el contenido binario, para que permite mostrar ciertos atributos aunque el retrieveContent sea false, a parte de añadir los cambios necesarios para el nuevo atributo, si quereis que os mande por correo un documento detallando todos los cambios (en qué documentos y línea) lo puedo preparar.

Por mi parte con este commit doy por solucionadas ambas incidencias

**Comment by dsariego-memorandum** [comment]
Se han revertido los cambios de la solución anterior y se han commiteado los cambios necesarios para realizarla como se comentó en el último comentario. 

Con estos cambios siempre devolverá como propiedades eni:fileSize y eni:mimeType el mimeType y tamaño en bytes del contenido.

**Comment by dsariego-memorandum** [comment]
Se han realizado los cambios hablados en la reunión para que los datos del mimeType y tamaño se devuelvan en las propiedades gdib:fileSize y eni:tamano_logico
