### ISSUE TITLE
Error al cerrar un expediente con contenido relacionado

### ISSUE THREAD

**Issue by tgaya-dgtic** [GovernIB/gdib#22]
Cuando cerramos un expediente que contiene documentos que tienen contenido relacionado con dos nodos del documento se borran físicamente los contenidos.

Se da en los casos que un documento tiene una firma detached. En estos casos existen dos contenidos relacionados con el documento, el propio documento y la firma. Al cerrarse el expediente, durante el proceso de transferencia del repositorio DM al RM se borran los contenidos de los documentos.

Esta incidencia está reportada a Alfresco y la solución pasa por actualizar la versión de RM, lo que indirectamente requiere de actualizar la versión de Alfresco.

(Tarea importada desde Redmine)

**Comment by cbernus-memorandum** [comment]
Falta comprobación en la máquina sdesalflin4, nuestras pruebas dieron resultados positivos y no fuimos capaces de reproducir el error utilizando los node id que nos sumunistró Toni Trobat.

**Comment by cbernus-memorandum** [comment]
Toni puedes llevar a cabo esta comprobación en la máquina sdesalflin4 ? Nosotros estuvimos llevando a cabo pruebas y parecia que el error se solucionó a través de la actualización del módulo del RM y de la versión de Alfresco, tal como se especifica en el ticket reportado a Alfresco.

**Comment by atrobat-dgtic** [comment]
Hola Carlos, nohe podido acceder a sdesalflin4, me daba un error. Pero he hecho la prueba en nuestro entorno migrado y he podido cerrar un expediente y recuperar el documento firmado junto con el fichero que contiene la firma.
