### ISSUE TITLE
Falta tamany de document i firma quan s'intenta obtenir informació d'un Document

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/gdib#3]
Afegir a l'API REST, informació del tamany en bytes del fitxer principal i de les firmes. Això s'haurà de fer una nova versió de GDIB API i potser modificar el CORE per a que retorni aquesta informació.

**Comment by dsariego-memorandum** [comment]
Lo he probado en desarrollo y sí devuelve información de las firmas, podeis volver a reproducir el error?

**Comment by dsariego-memorandum** [comment]
Se ha realizado la ampliación para que en el objeto Content, a parte del contenido en base64 y el tipo, se devuelva también el tamaño de este contenido.
Será necesario modificar el bus para que este nuevo atributo sea visible al llamar a través de este

**Comment by tgaya-dgtic** [comment]
Ok, nos podríais detallar en un documento los pasos a realizar para modicar el Bus y enviárnoslo por email.

**Comment by dsariego-memorandum** [comment]
Debido a que se trata de cambios en el mismo sitio para las incidencias #2 y #3, estas se han commiteado juntas.
Con estos cambios GDIB devolverá, siempre que se trate de un documento, información sobre el contenido del documento aunque este no se obtenga (tamaño del contenido, mimetype...).
Además, también se añaden cambios en el cliente jersey que serían necesarios para recoger este valor. Falta en este commit los cambios en el bus, los cuales se envían por correo, como nos pedisteis

**Comment by dsariego-memorandum** [comment]
Se commitean los cambios para las incidencias #2 y #3 juntas, en este commit se añaden unos cambios que faltaban cuando se intenta obtener un documento migrado, además, se arregla un error no reportado que había cuando el booleano de obtener contenido se ponía a false obteniendo estos documentos migrados, y los cambios en los archivos del esb necesarios para que muestre al exterior los nuevos datos.

Debido a que en una de las incidencias se pedía recuperar datos del mimeType aunque se pusiese a false el booleano de obtener el contenido, y la otra incidencia trataba de añadir un nuevo booleano de información del contenido, he aplicado la misma lógica para ambos atributos, para que se muestren siempre se desee recuperar el contenido o no (he comprobado que esto no afecta al tiempo de respuesta de la petición). Si no se quiere que se devuelva el tamaño de la firma cuando el booleano de obtener contenido sea false, decidmelo y haré otro nuevo commit cambiando esto (son unos cambios fáciles que no llevaría más de media hora hacer y probarlos)

En cuanto a los cambios del bus, como he dicho, están incluídos en este commit, se trata de unos cambios sobre la forma de tratar el contenido binario, para que permite mostrar ciertos atributos aunque el retrieveContent sea false, a parte de añadir los cambios necesarios para el nuevo atributo, si quereis que os mande por correo un documento detallando todos los cambios (en qué documentos y línea) lo puedo preparar.

Por mi parte con este commit doy por solucionadas ambas incidencias

**Comment by dsariego-memorandum** [comment]
Por lo tratado por correo, se procede a cambiar el desarrollo realizado para las incidencias #2 y #3.
Como comentasteis, existe una propiedad "eni:tamano_logico" en el modelo de Alfresco, pero esta propiedad forma parte del aspecto "eni:interoperable", este aspecto lo poseen los tipos "gdib:exp_original" y "eni:expediente".
Debido a esto, se procede a añadir dos nuevas propiedades "eni:tamano_logico_contenido" y "eni:mime_type" para los tipos "gdib:documentoMigrado" y "eni:documento", estas propiedades se pondrán como no obligatorias para evitar posibles problemas con todos los documentos ya existentes, pero se comprobará que estén informadas a la hora de la creación y obtención, y si no lo estuvieran, se hayarán a partir de su contenido para añadirse.

**Comment by dsariego-memorandum** [comment]
Buenas,

Después de analizar detalladamente el código, he observado que ya se está devolviendo una propiedad que se calcula el tamaño del documento en la devolución del nodo (no existe en el modelo de alfresco) que se llama "fileSize", cuyo namespace es "http://www.ricoh.es/model/gdib/calculated/1.0" (prefijo "calc")
Esta propiedad no se muestra al exterior porque no pasa el "filtro" que se hace en el código del bus, donde tiene declarados los namespaces que permite:
[...]
<xsl:variable name="eniUriNsLength" select="fn:string-length('{http://www.administracionelectronica.gob.es/model/eni/1.0}')" />
     	<xsl:variable name="gdibUriNsLength" select="fn:string-length('{http://www.caib.es/model/gdib/1.0}')" />
     	<xsl:variable name="cmUriNsLength" select="fn:string-length('{http://www.alfresco.org/model/content/1.0}')" />
[...]
y más adelante hace una sustitución de la URI por el prefijo de este namespace:
[...]
<xsl:when test="fn:starts-with(ws:type/text(),'{http://www.administracionelectronica.gob.es/model/eni/1.0}')">
	<csgd:type><xsl:value-of select="fn:concat('eni:',fn:substring(ws:type/text(),$eniUriNsLength+1))"/></csgd:type>
</xsl:when>
[...]

al igual que no se muestra esta propiedad, hay otras muchas que tampoco pasan este filtro, bastantes más que las que se muestran al final (adjunto captura de ejemplo)
![Captura](https://user-images.githubusercontent.com/71632820/98110645-b168c980-1e9f-11eb-8874-a580dc60a2e5.JPG)

En la petición realizada para esta prueba, solamente pinta las 8 propiedades con el namespace de eni de todas las mostradas. Me imagino que este filtro estará puesto por algo y no se deseará modificar el bus, por lo que propongo es cambiar el prefijo de esta propiedad calculada (o de las que queráis) por el de eni, para que así pase este filtro y se muestre en el exterior. De esta manera, al tratarlo como propiedades calculadas (que es lo que son realmente), la solución se simplifica bastante, ya que no hará falta modificar el modelo de Alfresco y únicamente se modificará el código en una parte en concreto

**Comment by dsariego-memorandum** [comment]
Se han revertido los cambios de la solución anterior y se han commiteado los cambios necesarios para realizarla como se comentó en el último comentario. 

Con estos cambios siempre devolverá como propiedades eni:fileSize y eni:mimeType el mimeType y tamaño en bytes del contenido.

**Comment by dsariego-memorandum** [comment]
Se han realizado los cambios hablados en la reunión para que los datos del mimeType y tamaño se devuelvan en las propiedades gdib:fileSize y eni:tamano_logico
