### ISSUE TITLE
Eliminar valor por defecto del metadato eni:def_csv

### ISSUE THREAD

**Issue by atrobat-dgtic** [GovernIB/gdib#31]
Este metadato sólo debería ser obligatorio en el caso que el tipo de firma del documento sea firma con csv, en el resto de casos no debería ir informado.

Actualmente GDIB lo considera obligatorio y debería poder no ser enviado por las aplicaciones i en le caso que se envíe vacío, que se informe como vacío. Ahora mismo si viene vacío se informa con un valor por defecto que pone def_csv_value.

**Comment by cbernus-memorandum** [comment]
Solucionado en sdesalflin4, en el commit referenciado en esta incidencia. Pendiente de cerrar.

**Comment by cbernus-memorandum** [comment]
Hay que reincidir, que para el correcto funcionamiento también será necesario modificar el valor eni:def_csv de los atributos donde aparezca en gdib-amp.properties.
