### ISSUE TITLE
Comprobar campos código clasificación e id. trámite

### ISSUE THREAD

**Issue by tgaya-dgtic** [GovernIB/gdib#32]
Comprobar si los campos "Código clasificación" e "Id. trámite" se están almacenando bien a través de llamadas de la API.

**Comment by cbernus-memorandum** [comment]
A la espera de recibir más feedback respecto a esta incidencia del entorno de pro  ya que en desarrollo parecía que se estuvieran almacenando correctamente estos campos.

**Comment by tgaya-dgtic** [comment]
Ayer estuve comprobando peticiones y respuestas que recibe el Bus. Para mí está todo Ok.
Le pedí a Asier algún ejemplo del fallo, por si fuera debido a la API de archivo, y dice que no es capaz de reproducirlo.

Pendiente de cerrar la incidencia.
