### ISSUE TITLE
Fitxers utf-8 amb codificació incorrecta

### ISSUE THREAD

**Issue by tgaya-dgtic** [GovernIB/gdib#34]
./gdib-amp/src/main/resources/alfresco/module/gdib-amp/transformers.properties
./gdib-amp/src/main/resources/alfresco/module/gdib-amp/integraFacade.properties
./gdib-amp/src/main/resources/alfresco/module/gdib-amp/afirma5ServiceInvoker.properties
./gdib-amp/src/main/resources/alfresco/module/gdib-amp/properties/gdib-amp.properties
./gdib-amp/src/main/resources/alfresco/module/gdib-amp/parserParameters.properties
./gdib-amp/src/main/resources/alfresco/extension/templates/webscripts/es/caib/limpiaPreingreso.txt
./gdib-amp/src/main/java/es/caib/gdib/ws/impl/AfirmaV6SignatureServiceImpl.java
./gdib-amp/src/main/java/es/caib/gdib/ws/impl/RepositoryServiceSoapPortImpl.java
./gdib-amp/src/main/java/es/caib/gdib/ws/iface/SignatureService.java
./gdib-amp/src/main/java/es/caib/gdib/rm/utils/ImportUtils.java
./gdib-amp/src/main/java/es/caib/gdib/behavior/CAIBRecordServiceImpl.java
./gdib-amp/src/main/java/es/caib/gdib/schedulejobs/ResealDocuments.java
./gdib-amp/src/main/java/es/caib/gdib/schedulejobs/UpgradeIndex.java
./gdib-amp/src/main/java/es/caib/gdib/utils/CaibIndexV10SignerImpl.java
./esb/RecursosRegistroCSGD/CreateNodeSequence.xml
./esb/RecursosRegistroCSGD/GetNodeSequence.xml
./esb/RecursosRegistroCSGD/SearchNodeSequence.xml
./esb/DocManagementProxyServices/src/main/synapse-config/proxy-services/generateDocCSV.xml
./esb/DocManagementProxyServices/src/main/synapse-config/proxy-services/grantPermissionsOnDocs.xml
./esb/DocManagementProxyServices/src/main/synapse-config/proxy-services/lockDocument.xml
./esb/DocManagementProxyServices/src/main/synapse-config/proxy-services/copyDocument.xml
./esb/DocManagementProxyServices/src/main/synapse-config/proxy-services/easyFileSearch.xml
./esb/DocManagementProxyServices/src/main/synapse-config/proxy-services/dispatchDocument.xml
./esb/DocManagementProxyServices/src/main/synapse-config/proxy-services/createDocument.xml
./esb/DocManagementProxyServices/src/main/synapse-config/proxy-services/removeFolder.xml
./esb/DocManagementProxyServices/src/main/synapse-config/proxy-services/removeFile.xml
./esb/DocManagementProxyServices/src/main/synapse-config/proxy-services/cancelPermissionsOnFolders.xml
./esb/DocManagementProxyServices/src/main/synapse-config/proxy-services/unlockFolder.xml
./esb/DocManagementProxyServices/src/main/synapse-config/proxy-services/createDraftDocument.xml
./esb/DocManagementProxyServices/src/main/synapse-config/proxy-services/setFinalDocument.xml
./esb/DocManagementProxyServices/src/main/synapse-config/proxy-services/grantPermissionsOnFiles.xml
./esb/DocManagementProxyServices/src/main/synapse-config/proxy-services/cancelPermissionsOnFiles.xml
./esb/DocManagementProxyServices/src/main/synapse-config/proxy-services/removeDocument.xml
./esb/DocManagementProxyServices/src/main/synapse-config/proxy-services/setFile.xml
./esb/DocManagementProxyServices/src/main/synapse-config/proxy-services/getEcmAutTicket.xml
./esb/DocManagementProxyServices/src/main/synapse-config/proxy-services/createChildFile.xml
./esb/DocManagementProxyServices/src/main/synapse-config/proxy-services/createFolder.xml
./esb/DocManagementProxyServices/src/main/synapse-config/proxy-services/lockFile.xml
./esb/DocManagementProxyServices/src/main/synapse-config/proxy-services/getFile.xml
./esb/DocManagementProxyServices/src/main/synapse-config/proxy-services/unlockDocument.xml
./esb/DocManagementProxyServices/src/main/synapse-config/proxy-services/getFileVersionList.xml
./esb/DocManagementProxyServices/src/main/synapse-config/proxy-services/getFolder.xml
./esb/DocManagementProxyServices/src/main/synapse-config/proxy-services/reopenFile.xml
./esb/DocManagementProxyServices/src/main/synapse-config/proxy-services/copyFolder.xml
./esb/DocManagementProxyServices/src/main/synapse-config/proxy-services/setDocument.xml
./esb/DocManagementProxyServices/src/main/synapse-config/proxy-services/mocks/DSSAfirmaVerifyMigratedDocMock.xml
./esb/DocManagementProxyServices/src/main/synapse-config/proxy-services/mocks/DSSAfirmaVerifyXAdESMock.xml
./esb/DocManagementProxyServices/src/main/synapse-config/proxy-services/mocks/SearchNodeByCSVMock.xml
./esb/DocManagementProxyServices/src/main/synapse-config/proxy-services/mocks/DSSAfirmaVerifyMock.xml
./esb/DocManagementProxyServices/src/main/synapse-config/proxy-services/mocks/GetNodeMock.xml
./esb/DocManagementProxyServices/src/main/synapse-config/proxy-services/mocks/SearchNodeMock.xml
./esb/DocManagementProxyServices/src/main/synapse-config/proxy-services/mocks/CreateNodeMock.xml
./esb/DocManagementProxyServices/src/main/synapse-config/proxy-services/mocks/CreateFileNodeMock.xml
./esb/DocManagementProxyServices/src/main/synapse-config/proxy-services/easyDocumentSearch.xml
./esb/DocManagementProxyServices/src/main/synapse-config/proxy-services/fileSearch.xml
./esb/DocManagementProxyServices/src/main/synapse-config/proxy-services/cancelPermissionsOnDocs.xml
./esb/DocManagementProxyServices/src/main/synapse-config/proxy-services/moveDocument.xml
./esb/DocManagementProxyServices/src/main/synapse-config/proxy-services/exportFile.xml
./esb/DocManagementProxyServices/src/main/synapse-config/proxy-services/linkDocument.xml
./esb/DocManagementProxyServices/src/main/synapse-config/proxy-services/moveFolder.xml
./esb/DocManagementProxyServices/src/main/synapse-config/proxy-services/transformMigratedDoc.xml
./esb/DocManagementProxyServices/src/main/synapse-config/proxy-services/unlockFile.xml
./esb/DocManagementProxyServices/src/main/synapse-config/proxy-services/moveChildFile.xml
./esb/DocManagementProxyServices/src/main/synapse-config/proxy-services/documentSearch.xml
./esb/DocManagementProxyServices/src/main/synapse-config/proxy-services/grantPermissionsOnFolders.xml
./esb/DocManagementProxyServices/src/main/synapse-config/proxy-services/getDocVersionList.xml
./esb/DocManagementProxyServices/src/main/synapse-config/proxy-services/linkFile.xml
./esb/DocManagementProxyServices/src/main/synapse-config/proxy-services/linkFolder.xml
./esb/DocManagementProxyServices/src/main/synapse-config/proxy-services/generateFileIndex.xml
./esb/DocManagementProxyServices/src/main/synapse-config/proxy-services/closeFile.xml
./esb/DocManagementProxyServices/src/main/synapse-config/proxy-services/getDocument.xml
./esb/DocManagementProxyServices/src/main/synapse-config/proxy-services/setFolder.xml
./esb/DocManagementProxyServices/src/main/synapse-config/proxy-services/lockFolder.xml
./esb/DocManagementProxyServices/src/main/synapse-config/proxy-services/getENIDocument.xml
./esb/JavaMediators/src/main/resources/transformers.properties
./esb/JavaMediators/src/main/resources/parserParameters.properties

**Comment by tgaya-dgtic** [comment]
Vamos a ver, el único trabajo que tenía que hacerse con estos ficheros es abrirlos y grabarlos como ficheros con codificación UTF8.
Creo que no es algo tan difícil de entender (siempre que seáis informáticos, claro).

**Comment by dsariego-memorandum** [comment]
Se hace revert del anterior commit, he vuelto a bajar gdib entero del repositorio y he comprobado que los ficheros están codificados correctamente, utf-8 o us-ascii, estas dos codificaciones son la misma:

"us-ascii and utf-8 are the same in the lower 7 bits (0-127), aka all of the English characters. So there is no difference"

la razón por la que algunos ficheros se guardan como us-ascii es porque no contienen ningún carácter utf-8.

Se ha de asegurar que cualquier persona que toque el repositorio se asegure de tener configurado correctamente su entorno, ya que cada vez que toque algún fichero codificado en utf-8, si él no lo tiene codificado correctamente, puede camabiar esta codificación y volver al mismo problema. Los comentarios en las clases no tienen solución, al no ser que se codifique en inglés, pero la posible solución para los ficheros de propiedades y líneas de log es escapar los caracteres.

**Comment by tgaya-dgtic** [comment]
Como hemos hablado por teléfono, mira este commit y verás el por qué teníais que arreglar las codificaciones de la carpeta gdib-amp.
https://github.com/GovernIB/gdib/commit/21f2c811c65cbe8bf4998152e1f229aafc44bf58#diff-17c5a694c9914ca942b7f2e0cf595e4b9bd8144423c1d82d07d2006a79470d51

**Comment by dsariego-memorandum** [comment]
Como hablamos por teléfono, con los cambios commiteados ayer, ya está cambiado el formato del repositorio a UTF-8 y se ha solucionado los problemas con unos pocos caracteres corruptos que había en algunas clases, los demás caracteres propios del formato UTF-8 siguen viéndose como ?, aunque al imprimir los interpreta correctamente (ya que en los ficheros XML vienen con la codificación definida en la cabecera). 
Por lo hablado por teléfono entiendo que la incidencia ya está resuelta, ¿Es así?

**Comment by tgaya-dgtic** [comment]
Vale, ahora los ficheros de la carpeta gdib-amp están en formato utf8.
Lo que pasa que con vuestro commit https://github.com/GovernIB/gdib/commit/4274801f00770ced94d5142215dd08b628b68fb7#diff-f0925dfad0502a7b27e0b61a8dc553a4ef190fa497a4a0db43af5e08d5333d32 machacásteis los acentos, etc, con algún formato raro y al volver a pasarlo a utf8 se han quedado algunas letras mal codificadas.

De todas formas, no vale la pena perder más tiempo en este tema y menos que los commits de esta incidencia os líen y encima deshagáis commits de nuevos trabajos. Voy a dar la incidencia por 'imposible' y la cierro.
