### ISSUE TITLE
Resellado: cambio indice_valido y métodos involucrados

### ISSUE THREAD

**Issue by tgaya-dgtic** [GovernIB/gdib#36]
En el campo indice_valido, añadir el valor “SI_PERMANENTE” a los expedientes que ya no se deban resellar más, y modificar los métodos que devuelven el índice, devuelvan el que tiene el valor “SI” o “SI_PERMANENTE”.

**Comment by cbernus-memorandum** [comment]
Actualmente, una vez un documento ha pasado el periodo de vigencia, ya no se resellará, pero tengo entendido que es posible que una serie ya posea un valor de resellado que indique que no se han de resellar, necesitaría saber cual es ese valor para establecerlo y añadirlo al funcionamiento, con eso ya podré terminar la incidencia

**Comment by tgaya-dgtic** [comment]
En principio, existe el período de validez jurídica (que es el tiempo durante el cual se tiene que ir resellando un documento) y el período de conservación (que es el tiempo durante el cual se tiene que conservar el documento en el sistema sin purgarlo, o sea, sin borrarlo).

**Comment by cbernus-memorandum** [comment]
Me refiero a que actualmente, el período que determina que un documento deba ser resellado, se obtiene a partir del valor de la columna resellado, escrito en días, de la tabla del cuadro de clasificación actual. Pero creo que hay posibles valores que indican tanto que ese documento no deba resellarse, como que deban resellarse siempre. Para aprovechar el nuevo valor SI_PERMANENTE , necesito controlar cual es ese valor para tenerlo en  cuenta a la hora de asignar el metadato de indice_valido
Un saludo

**Comment by cbernus-memorandum** [comment]
Es decir, corrígeme si me equivoco  ¿ el único caso para el cual se usará el SI_PERMANENTE, será en aquellos expedientes que hayan sobrepasado su validez jurídica ? 
De esta manera una vez hayan superado su validez jurídica los expedientes ya no volverán a resellar, mientras que conservarán la funcionalidad actual contemplando el ultimo indice valido como el que posea el SI_PERMANENTE.

**Comment by tgaya-dgtic** [comment]
Correcto.
