### ISSUE TITLE
Generar un fichero de log independiente donde se muestre toda la actividad de GDIB

### ISSUE THREAD

**Issue by atrobat-dgtic** [GovernIB/gdib#38]
El objetivo de esta tarea es configuar el log de Afresco para que vaya volcando toda la información de log que genera GDIB i las consultas a @firma en un fichero de log que vaya rotando diariamente. La intención es poder hacer un seguimiento de las peticiones que se envian al Arxiu desde que llega una petición hasta que devuelve la respuesta.  El objetivo también es poder configurar de manera más sencilla los niveles de log que se quieren mostrar de las diferentes clases java que intervienen durante todo el proceso.

**Comment by dsariego-memorandum** [comment]
Se ha commiteado los cambios en el fichero de log precisos para que:
-Todos los logs de gdib se guardan dentro de la carpeta [alfresco_home]/tomcat/logs/gdib/
-Cada job genera su propio fichero de log
-Toda la traza de las peticiones realizadas a los servicios de Repository, Migration o CSV se guardan en un fichero gdib.log
-Todos los logs se rotan una vez al día
-Los ficheros de log antiguos se guardan con la forma 'xxxx.log.yyyy-MM-dd' (por ejemplo gdib.log.2020-11-06)

Si queréis, a mayores podría configurar un fichero de log que guarde solamente todos los errores producidos en gdib (en las llamadas a los servicios o jobs)

**Comment by atrobat-dgtic** [comment]
En el fichero de log del proceso de resellado se podría hacer que gdib muestre la siguiente información al lanzarse el proceso diario de resellado:

Total de documentos a resellar en DM: 
Total de expedientes a resellar en RM:

**Comment by cbernus-memorandum** [comment]
Actualmente los trabajos de resellado tienen configurados Logs por separados.
Además durante la ejecución  se lleva a cabo a partir de hacer queries en base a el código de clasificación, en cada query aparece el número de resultados obtenidos.
Teniendo eso en cuenta, ¿queréis que ajustemos el log para que imprima ese mensaje igualmente? Habría que modificar un poco el código de ambos jobs

**Comment by atrobat-dgtic** [comment]
La idea es tener visualmente una idea de lo que se va a resellar. Seria mas fácil ir guardando la información durante el proceso y mostrarla al final de todo? Si es así también iria bien i en lugar de mostrar el mensaje anterior mostrar:

Total de documentos resellados en DM:
Total de expedientes resellados en RM:

 Aprovecho para hacerte una consulta,  el proceso de resellado queda auditado en gdib?

**Comment by cbernus-memorandum** [comment]
Cuando dices auditado te refieres a las inserciones en la base de datos de auditoría?

**Comment by atrobat-dgtic** [comment]
Si, correcto.

**Comment by cbernus-memorandum** [comment]
Actualmente inserciones en esa base de datos solamente se llevan a cabo en las peticiones de los web-services, así que las operaciones de resellado / upgradeo de índices no están interactuando con esa bbdd actualmente. 
Tal como está programado es un interceptor de peticiones web que hace inserciones en la bbdd de auditoría que tengais configurada con las peticiones que les llegan.
