### ISSUE TITLE
Documentar cambios en el Bus

### ISSUE THREAD

**Issue by tgaya-dgtic** [GovernIB/gdib#39]
Documentar los cambios que son necesarios realizar en el Bus, en el paso a Alfresco 6.2 + gdib 1.5.

**Comment by dsariego-memorandum** [comment]
Buenas tardes,

Os he enviado por correo el documento detallando los cambios a realizar y como aplicarlos. Los cambios en el código detallados en el documento están también commiteados referenciando las incidencias #2 y #3 

Un saludo
