### ISSUE TITLE
Perdem el nom de la firma quan el Document és una Firma Detached

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/gdib#4]
En el cas de firmes detached de tipus CAdES o XAdES, perdem el  el nom de la firma, ja que només es guarda el mimetype i el contingut.
Fer que el Mòdul de GDIb també guardi el nom de la firma en el cas de detached.

**Comment by atrobat-dgtic** [comment]
Se refiere a que en una firma detached se suben dos contenidos a un documento electrónico, un es el propio documento, el otro la firma. El problema es que al no guardarse el nombre del fichero de la firma si en algún momento se quiere descargar obtenemos un fichero con un nombre x diferente del que se guardó en le archivo. Se trataria de guardar el nombre de este fichero para que cuando se descargue, se pueda descargar con el nombre original que tenia.
