### ISSUE TITLE
Error en la operacion setDocument

### ISSUE THREAD

**Issue by atrobat-dgtic** [GovernIB/gdib#41]
Hemos detectado que al crear una nueva versión de un documento se genera un error.  Esta acción ejecuta la operación setDocument del bus de servicios y  devuelve la siguiente excepción:

<S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/">
   <S:Body>
      <jsonObject>
         <exception>
            <code>COD_021</code>
            <description>java.lang.NullPointerException</description>
         </exception>
      </jsonObject>
   </S:Body>
</S:Envelope>

**Comment by dsariego-memorandum** [comment]
Se ha solucionado el error, por error no había commiteado el modelo de alfresco en el que añadía la nueva propiedad 'gdib:mimeType' con relación a la incidencia #2 . Ya está commiteado, será necesario redesplegar el amp para que se haga efectivo el cambio del modelo.

Perdón por las molestias,

Un saludo
