### ISSUE TITLE
Mejora de rendimiento: Hacer en segundo plano el upgrade de firma de los documentos que entran en el archivo

### ISSUE THREAD

**Issue by atrobat-dgtic** [GovernIB/gdib#43]
Se trata de una tarea orientada a mejorar el tiempo de respuesta de GDIB hacia las aplicaciones. Consiste en que cuando una aplicación guarde un documento firmado en el archivo no tenga que esperar a que se haga el upgrade de firma para obtener la respuesta de GDIB. Simplemente se tendría que hacer la validación de la firma. Entonces se tendría que crear un proceso que en segundo plano vaya haciendo el upgrade de firma de los documentos.

Antes de abordar este punto os pedimos que hagáis un análisis para estimar el coste de esta mejora.

**Comment by tgaya-dgtic** [comment]
Implementado en gdib-v1.5.1. Pendiente de probar.
