### ISSUE TITLE
Mejora de rendimiento: Operación de cerrar un expediente en segundo plano

### ISSUE THREAD

**Issue by atrobat-dgtic** [GovernIB/gdib#44]
Se trata de una tarea para mejorar el tiempo de respuesta de GDIB hacia las aplicaciones. Cerrar un expediente es una de las operaciones más costosas en cuanto a tiempo de las que se hacen en el archivo. Lo que se busca es que una aplicación de la orden de cerrar un expediente y luego pase a ser GDIB el que se encargue de hacer la operación en segundo plano, de manera que se responda a la aplicación con un ok casi instantáneo a la petición de cerrar un expediente.

Antes de implementar esta tarea, os pedimos un análisis  previo para estimar su dificultat i coste.

**Comment by tgaya-dgtic** [comment]
Implementado en gdib-v1.5.1. Pendiente de probar.
