### ISSUE TITLE
Resellejat el dia següent a la seva creació.

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/gdib#5]
* ARXIU de DES.
* Fitxer URL: https://afirmades.caib.es:4430/share/page/document-details?nodeRef=workspace://SpacesStore/84d4dcfb-cecc-406b-830d-e9cc94688c0a

Dia 13 de desembre de 2017 es va crear un expedient i s'hi vaig ficar un fitxer definitiu (183352.pdf). Segons les dades del fitxer dia 14 de desembre de 2017 a les 0:00 hores es va tornar a resellejar el fitxer.

Problemes:
    (1) Com pot ser que la mateixa nit de la inclusió dins de l'Arxiu s'hagi resellejat?
   (2) Com és que alfresco no pot fer una provisualització d'un documetn amb dos sellejats de temps ? (veure captura d'Alfresco)

Es va comentar aquest cas a la gent de la CAIB: Veure mails de dia 14/12/2017 entre les 13:00 i 13:57

[183352.pdf](https://github.com/GovernIB/gdib/files/1575271/183352.pdf)

![imatge](https://user-images.githubusercontent.com/17084256/34204429-d8e804f6-e57e-11e7-8600-3b23bcfcb04c.png)

![imatge](https://user-images.githubusercontent.com/17084256/34204201-1adca34a-e57e-11e7-8828-d40cc92aa447.png)

**Comment by atrobat-dgtic** [comment]
Actualment es canvia el criteri de resegellat al DM, es resegellarà quan detectem que el certificat del segell de temps que es posa a l'ingrés a l'arxiu està a punt de caducar. Aquesta casuística ja no es donarà.
