### ISSUE TITLE
Quan es passa l'expedient a RM el nom dels fitxers es modifiquen

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/gdib#6]
En les imatges podem veure el fitxer d'un expedient abans i després de tancar-ho i que que es mogués a RM. A més, quan està a RM, si consultes el fitxer et diu que el títol és "DOC_aea3d458f1654016a7e08bd8e5a811f9 (2017-1513860082111)" enlloc de "183352.pdf"

![imatge](https://user-images.githubusercontent.com/17084256/34289204-a748324e-e6f1-11e7-9254-405a76d8f497.png)

![imatge](https://user-images.githubusercontent.com/17084256/34289207-abcc971a-e6f1-11e7-9d61-5f2522a5f7b4.png)

**Comment by atrobat-dgtic** [comment]
Aquesta incidència es va resoldre a l'anterior contracte de manteniment de l'arxiu.
