### ISSUE TITLE
API REST: COD_021-java.lang.IndexOutOfBoundsException al cridar a busquedaFacilExpedientes()

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/gdib#8]
De forma aleatòria es produeixen IndexOutOfBoundsException al fer cridades a busquedaFacilExpedientes de API REST. Pareix que l'error arriba de l'Alfresco. Això passava en regweb3, però es va afegir 

```
FiltroBusquedaFacilExpedientes filtrosRequeridos = new FiltroBusquedaFacilExpedientes();
        filtrosRequeridos.setName(nomExpedient);
        filtrosRequeridos.setAppName(getPropertyCodiAplicacio());
        String serieDocumental = processEL(getPropertySerieDocumentalEL(), custodyParameters);
        filtrosRequeridos.setDocSeries(serieDocumental);
        
        if (debug) {
          log.info(" CERCA[Name] => " + filtrosRequeridos.getName() );
          log.info(" CERCA[AppName] => " + filtrosRequeridos.getAppName() );
          log.info(" CERCA[serieDocumental] => " + filtrosRequeridos.getDocSeries());
        }
        
  
        ResultadoBusqueda<Expediente> res = api.busquedaFacilExpedientes(filtrosRequeridos,
            null, 1);
```

**Comment by anadal-fundaciobit** [comment]
Aqui hi ha un exemple que en PRO falla:

´´´
public static void provaCerca(ApiArchivoDigital api) throws Exception {
 
 

      FiltroBusquedaFacilExpedientes filtrosRequeridos = new FiltroBusquedaFacilExpedientes();
      filtrosRequeridos.setName("L15-E-25021_2017");
      filtrosRequeridos.setAppName("REGWEB");
      filtrosRequeridos.setDocSeries("A57");
    


      ResultadoBusqueda<Expediente> res = api.busquedaFacilExpedientes(filtrosRequeridos,  null, 1);


     if (hiHaErrorEnCerca(res.getCodigoResultado())) {
        throw new Exception("Error Consultant si Expedient existeix: "
             + res.getCodigoResultado() + "-" + res.getMsjResultado());
      }

      List<Expediente> llista2 = res.getListaResultado();

    
      if (llista2.size() == 0) {
        System.out.println("Llista Buida");
      } else {
        for (Expediente expediente : llista2) {
          System.out.println(" Expedient trobat: " + expediente.getName() + "(" + expediente.getId() + ")");
        }
      }
  }
 
  public static boolean hiHaErrorEnCerca(String code) {
    return !CodigosResultadoPeticion.PETICION_CORRECTA.equals(code)
        && !CodigosResultadoPeticion.LISTA_VACIA.equals(code);
  }
´´´

**Comment by cbernus-memorandum** [comment]
Sería posible obtener parte del log de esta incidencia?

**Comment by tgaya-dgtic** [comment]
No disponemos de los logs, porque es una incidencia muy antigua.

Tendrías que intentar volver a reproducir el error.

**Comment by cbernus-memorandum** [comment]
```
 ResultadoBusqueda<Expediente> res = api.busquedaFacilExpedientes(filtrosRequeridos,
            null, 1);

```
Entiendo, que cuando haceis uso de la API REST como en este caso, cuando escribís la página 1, os estais refiriendo a la 1 y no a la 0 no?

**Comment by tgaya-dgtic** [comment]
Si es una copia del trozo de código, se entiende que falla tal cual.
Si pone 1 es que es 1 y no 0.

**Comment by cbernus-memorandum** [comment]
Revisando el commit https://github.com/GovernIB/gdib/commit/a22a858fb068c26f1f8ab73707d87fbcb3e370e4#diff-9bb88d923bab2bc3dd0a1d6682a1ee71cc7019f4c028fcbb51a7937be370e5cc
que es del día posterior a abrir esta incidencia, podemos observar que se controló correctamente ese error, por eso no he conseguido reproducirlo, era la única opción que faltaba por revisar. 
![image](https://user-images.githubusercontent.com/61832001/96268971-05337180-0fca-11eb-93d9-1822eceff36d.png)

**Comment by tgaya-dgtic** [comment]
Pues entonces, supongo que se puede cerrar.
