### ISSUE TITLE
Error quan hi ha caràcters especials dins nom de l'interessat

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/gdib#9]
Quan s'envia un Justificant des de registre a Arxiu dóna un error quan en el nom de l'interessat hoi ha algun tipus de caràcter especial o reservat per URL o XML. En el cas de l'error el nom de l'interessat contenia una "&" i va llançar l'error següent:
```
Caused by: org.fundaciobit.plugins.documentcustody.api.CustodyException: Error creant expedient L11-E-2068_2018: COD_020-[com.ctc.wstx.exc.WstxLazyException] Unexpected character ' ' (code 32) (missing name?)
    at es.caib.regweb3.persistence.ejb.AnexoBean.crearJustificante(AnexoBean.java:1343)
```

**Comment by cbernus-memorandum** [comment]
Tal como establecen los estándares de W3C https://www.w3.org/TR/REC-xml/#syntax a la hora de parsear XMLs deben evitarse carácteres como < o & , para evitar este error, tal como pone en el link
The ampersand character (&) and the left angle bracket (<) must not appear in their literal form, except when used as markup delimiters, or within a comment, a processing instruction, or a CDATA section. If they are needed elsewhere, they must be escaped using either numeric character references or the strings " &amp; " and " &lt; " respectively. The right angle bracket (>) may be represented using the string " &gt; ", and must, for compatibility, be escaped using either " &gt; " or a character reference when it appears in the string " ]]> " in content, when that string is not marking the end of a CDATA section.
Es decir, para evitar el error, en caso de querer introducir esos carácteres, habría que poner "&amp;"  para el caracter "&" o "&gt;" para el carácter "<" , otra opción sería modificar el archivo  javascript en el servidor del bus de servicios, para utilizar un regex para cambiar automaticamente esos carácteres o añadir la sección CDATA.

**Comment by cbernus-memorandum** [comment]
`&amp;` y `&gt;` eran los valores respectivos que hay que añadir

**Comment by tgaya-dgtic** [comment]
Sí, si sólo es xml, se debería hacer con algún método:

se debería sustituir " por &quot;
se debería sustituir & por &amp;
se debería sustituir ' por &apos;
se debería sustituir < por &lt;
se debería sustituir > por &gt;

**Comment by cbernus-memorandum** [comment]
Claro pero para ello, lo podemos hacer sustituyéndolos en la función que construye la petición soap en el bus de servicios, pero creo que para ello tendríamos que tener acceso al servidor donde está instalado para poder modificar el archivo javascript que la contiene. Actualmente no tenemos acceso a ese servidor.

**Comment by tgaya-dgtic** [comment]
Ok, perdona, no había entendido la magnitud del problema.

Entonces el cambio se deberá hacer en el API de archivo, que son las librerías que usan las aplicaciones para llamar a gdib a través del bus.

**Comment by dsariego-memorandum** [comment]
Se utiliza librería de apache para escapar los caracteres especiales con los que el bus de servicios tiene problemas, se ha identificado el mismo problema en diferentes atributos.
Para solucionar esta incidencia es necesario que se actualicen el cliente jersey con el que hacen las llamadas con los cambios commiteados

**Comment by tgaya-dgtic** [comment]
Vamos a ver, los cambios se tienen que hacer en los clientes, antes de enviar el xml en la petición Soap.
En gdib no es necesario hacer ningún cambio porque no servirá de nada.

**Comment by dsariego-memorandum** [comment]
Buenos días,

Sí, en el cliente es donde están hechos los cambios.

Un saludo

**Comment by tgaya-dgtic** [comment]
A ver, las aplicaciones usan este cliente https://github.com/GovernIB/pluginsib-arxiu (mantenido por otra empresa), que proporciona una API SOAP (xml) que traduce las llamadas SOAP a REST, y es ahí donde se deben hacer los cambios (por la otra empresa).

Si haces cambios en el API REST (json) que proporciona gdib, no debería afectar o al menos no afectar de la misma forma, porque la API rest usa json, no xml.

**Comment by cbernus-memorandum** [comment]
Si Toni, el tema está que en el bus de servicios se transforman estas llamadas REST a SOAP de nuevo para mandarlas a GDIB, y es en este punto, cuando llegan estos carácteres extraños en formato JSON, el bus de servicios los concatena directamente mediante el archivo https://github.com/GovernIB/gdib/blob/master/esb/RecursosRegistroCSGD/serviceHeaderUtils.js para crear la petición XML que llegará a GDIB. El problema radicaba, como hemos expuesto que las librerías de Alfresco  encargadas de parsear estos mensajes no admitían estos carácteres en el formato XML, y pensabamos que las aplicaciones clientes utilizaban el cliente definido en gdib-apirest.
En ese caso, habrá que llevar a cabo esos cambios en el cliente que comentas para que escapen los carácteres anteriormente nombrados antes de mandar la petición REST en formato JSON al bus de servicios.

**Comment by tgaya-dgtic** [comment]
Si hi ha més problemes, pendent de que facin els canvis XML a l'API d'arxiu.
Avisats per email.
